SET FOREIGN_KEY_CHECKS=0
;

DROP TABLE IF EXISTS `CLIENTE` CASCADE
;

DROP TABLE IF EXISTS `TARJETA` CASCADE
;

DROP TABLE IF EXISTS `TRANSACCION` CASCADE
;

CREATE TABLE `CLIENTE`
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`IDENTIFICACION` VARCHAR(13) NOT NULL,
	`NOMBRE` VARCHAR(100) NOT NULL,
	`DIRECCION` VARCHAR(50) NOT NULL,
	`TELEFONO` VARCHAR(50) NOT NULL,
	`CORREO` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_CLIENTE` PRIMARY KEY (`ID` ASC)
)
;

CREATE TABLE `TARJETA`
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`CLIENTE_ID` INT NOT NULL,
	`TIPO` VARCHAR(3) NOT NULL,
	`NUMERO` VARCHAR(16) NOT NULL,
	`CVV` VARCHAR(255) NOT NULL,
	`FECHA_CADUCIDAD` DATE NOT NULL,
	`FECHA_EMISION` DATE NOT NULL,
	CONSTRAINT `PK_TARJETA` PRIMARY KEY (`ID` ASC)
)
;

CREATE TABLE `TRANSACCION`
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`TARJETA_ID` INT NOT NULL,
	`ESTADO` VARCHAR(3) NOT NULL,
	`FECHA_HORA` TIMESTAMP NOT NULL,
	`VALOR` DECIMAL(11,2) NOT NULL,
	`COMISION` DECIMAL(11,2) NOT NULL,
	`ES_DIFERIDO` BOOL NOT NULL,
	`FECHA_ACTUALIZACION` TIMESTAMP NOT NULL,
	CONSTRAINT `PK_TRANSACCION` PRIMARY KEY (`ID` ASC)
)
;

ALTER TABLE `CLIENTE` 
 ADD INDEX `IX_IDENTIFICACION` (`IDENTIFICACION` ASC)
;

ALTER TABLE `TARJETA` 
 ADD INDEX `IXFK_TARJETA_CLIENTE` (`CLIENTE_ID` ASC)
;

ALTER TABLE `TRANSACCION` 
 ADD INDEX `IXFK_TRANSACCION_TARJETA` (`TARJETA_ID` ASC)
;

ALTER TABLE `TRANSACCION` 
 ADD CONSTRAINT `CHK_ESTADO` CHECK (ESTADO IN ('PEN', 'APR', 'REC', 'REV'))
;

ALTER TABLE `TARJETA` 
 ADD CONSTRAINT `FK_TARJETA_CLIENTE`
	FOREIGN KEY (`CLIENTE_ID`) REFERENCES `CLIENTE` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `TRANSACCION` 
 ADD CONSTRAINT `FK_TRANSACCION_TARJETA`
	FOREIGN KEY (`TARJETA_ID`) REFERENCES `TARJETA` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;

